// <auto-generated />
using System;
using MVC_CRUD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC_CRUD.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MVC_CRUD.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Artist")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Artist = "Jane Doe",
                            Date = new DateOnly(2023, 8, 1),
                            Title = "Music Fest",
                            VenueId = 1,
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            Artist = "John Smith",
                            Date = new DateOnly(2024, 5, 15),
                            Title = "Tech Expo",
                            VenueId = 2,
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            Artist = "Alice Lee",
                            Date = new DateOnly(2025, 11, 20),
                            Title = "Art Show",
                            VenueId = 3,
                            Year = 2025
                        });
                });

            modelBuilder.Entity("MVC_CRUD.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventId = 1,
                            Price = 50m,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            EventId = 2,
                            Price = 75m,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            EventId = 3,
                            Price = 100m,
                            UserId = 3
                        });
                });

            modelBuilder.Entity("MVC_CRUD.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Surname")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            Name = "Alice",
                            Surname = "Johnson"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            Name = "Bob",
                            Surname = "Smith"
                        },
                        new
                        {
                            Id = 3,
                            Email = "charlie@example.com",
                            Name = "Charlie",
                            Surname = "Brown"
                        });
                });

            modelBuilder.Entity("MVC_CRUD.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Location = "Downtown",
                            Name = "Grand Hall"
                        },
                        new
                        {
                            Id = 2,
                            Location = "Uptown",
                            Name = "Open Arena"
                        },
                        new
                        {
                            Id = 3,
                            Location = "Midtown",
                            Name = "Conference Center"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
